### PR TITLE
Add project documentation

### PR DESCRIPTION
**Pull request by yoonspark**
# Description

This PR adds contents to the project documentation.

# Testing

You need the repo's dev environment to test/update MkDocs. For this, first install Poetry following instructions [here](https://python-poetry.org/docs/#installation). Then, at the repo's root level, run:

```bash
# Install dependencies including dev ones
poetry install --with dev

# Activate virtual environment
poetry shell
```

Once the dev environment is activated, run:

```bash
cd docs/
mkdocs serve
```

This will start a local development server for MkDocs, which can be accessed at `http://127.0.0.1:8000`.

# Addressed Issues

- #80

### CODE REVIEW

**Review by cswaney — COMMENTED** [review]
The overall structure looks good. I've provided some (mostly grammatical) edits. Accept or reject them as you see fit. You should ask Sylvain for input on the index page in addition to relevant technical sections. The research should probably be more prominent. I wonder if the "Garbling" page could be moved to the "Guides" section or else brought up to the index page (because there is really only the one main concept).

**Comment by yoonspark** [comment]
Adding new contents (code overview, deployment example) as per PI request.

**Comment by yoonspark** [comment]
@sylvaingchassang I've added new contents you requested:

- Overview of Codebase
- Example of Deployment on Render

Please feel free to make your updates to the project documentation here in this PR. Once you are good, we can merge the PR.

**Comment by yoonspark** [comment]
Merging this PR as a formal wrap-up of the project. Further changes, if desired, can be made through separate PRs.

**Pull request merged**
